# Generated by Django 2.2.10 on 2022-05-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(error_messages={'blank': "Choice text can't be empty", 'null': "Choice text can't be empty"}, max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question.Question')),
            ],
            options={
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
