# Generated by Django 2.2.10 on 2022-05-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choice', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoiceJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_journal', to='choice.Choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User')),
            ],
            options={
                'verbose_name_plural': 'User choices journal',
            },
        ),
    ]
