# Generated by Django 2.2.10 on 2022-04-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('user', '0001_initial'),
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.User')),
            ],
            options={
                'verbose_name_plural': "User-Quiz's journal",
            },
        ),
        migrations.CreateModel(
            name='UserChoiceJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='choice.Choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User')),
            ],
            options={
                'verbose_name_plural': 'User-Choices journal',
            },
        ),
    ]
