# Generated by Django 2.2.10 on 2022-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoicejournal',
            name='answer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
