# Generated by Django 2.2.10 on 2022-04-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquizjournal',
            options={'verbose_name_plural': 'User-Quizzes journal'},
        ),
    ]
