# Generated by Django 2.2.10 on 2022-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20220505_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoicejournal',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_journal', to='choice.Choice'),
        ),
    ]
