# Generated by Django 2.2.10 on 2022-05-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('quiz', '0001_initial'),
        ('journal', '0003_auto_20220505_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoicejournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choices', to='user.User'),
        ),
        migrations.CreateModel(
            name='UserQuizJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_journal', to='quiz.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to='user.User')),
            ],
        ),
    ]
