# Generated by Django 2.2.10 on 2022-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A quiz with that name already exists.'}, max_length=300, unique=True)),
                ('date_start', models.DateField(error_messages={'blank': 'Date start is not set up.', 'null': 'Date start is not set up.'})),
                ('date_end', models.DateField(error_messages={'blank': 'Date end is not set up.', 'null': 'Date end is not set up.'})),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
