name: linter-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Setup dependencies
        run: |
          pip3 install poetry
          make install

      - name: Lint
        run: make lint
